appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: AN65musWZLhK87Vj/39UAlAUZpMe8qrxPQ+Q+na5AFK/UdEjqnbemzJP3Jq3f1GsESC+MU2VL9GwxrrfxKt5EcySHl3EjyQOBCMTK0Menl/CfUKaEv5FEW0qCz0Y4/DyIdPGuz1kr55s/DEsePYpDalGGpFb32KbxoQGhucKfXIMEie/Wx+KXCgzODU0etYTbZatqLM/lyUJJCOiRRSvkgr1ZMhscmef+ZxqQaa/dST5Bi2TXyGmWGZjuU2iM7kNkD2n461hUg/8mO8vyRZFXH3n4jb2HPBhI9I3giLm4vB7rwAWKiI2xMipncRBkGQNU/ZrYij6mqBoSwMpSQut2QHXkb8zauuM+KmL4rkTX+X9ZaYJVtNS1veac6bPSc4jRaDlIUDSxeaq0WSt1oal3awy37zxohdUK1E63lS4YoRzOkQycTJmc7155CyHfMWv1uGsNconxFHLcnrrrzoBEKHTMQ09BQeOoqJcRyvFzZ83bW8aVhm9ZwOeheLMRjZofo0A28XZYzdMGUzjGe+N25lfU8vHsfIPyYk60x9lMS0nSqJSFEjMN1e1bH9i7CiHyZ9GrkPeuC7G4VWp2ggiusFBwft2TeetmkLxv0UegYKL/KZphq8KCjWDyd+gdUtlNpZUe+gq0G9rADKBx62su8jK1ltwqs1/Ael/oxuUyyE=}
